books:
  show:
    default_image: "default_book.png"
    words: 20
user:
  avatar_default: "default_avatar.png"
page:
  per: 12
  comment: 5
new_books: 6
icons: "library.png"
comment:
  content:
    maximum: 255
    minimum: 10
borrow:
  validate_date: "Start date should be before end date"
  not_over_7_days: "not over 7 days"
  bigger_time_now: "Time is shorter than time"
  day: 7
  per_page: 10
  index: 1
autocomplete:
  limit: 5
no_image: "noImageAvailable.jpg"
round: 2
